on: [push]
jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    container:
      image: brushlow/nordic_ses:latest
    steps:
      - uses: actions/checkout@v3
      - name: Perform build
        run: emBuild -config "Debug" ./src/nRF5_SDK_17.1.0_ddde560/examples/peripheral/blinky/pca10056/blank/ses/blinky_pca10056.emProject
      - name: Get build artifact
        uses: actions/upload-artifact@v2
        with: 
          path: ./src/nRF5_SDK_17.1.0_ddde560/examples/peripheral/blinky/pca10056/blank/ses/Output/Debug/Exe/blinky_pca10056.hex

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++ src.
      uses: jidicula/clang-format-action@v4.10.2
      with:
        clang-format-version: '13'
        check-path: 'src/nRF5_SDK_17.1.0_ddde560/examples/peripheral/blinky/'
        
  cppcheck:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          
        
      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main' # your branch name goes here
